apiVersion: v1
kind: PersistentVolume
metadata:
  name: store-pv
  namespace: default
spec:
  storageClassName: standard
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  readOnly: false