apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: store-claim
  namespace: default
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi