apiVersion: v1
kind: Service
metadata:
  labels:
    app: store
  name: server-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5006
  selector:
    app: store