apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
  namespace: default
spec:
  selector:
    matchLabels:
      app: store
  replicas: 2
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
      - name: store-container
        image: anchal00/store:tagname
        imagePullPolicy: IfNotPresent
        imagePullSecrets:
        - name: docker-credentials
        env:
        - name: port
          value: 5006
        - name: server-address
          value: server-service
        volumeMounts:
        - mountPath: /store/storage
          name: store-storage
      volumes:
      - name: store-storage
        persistentVolumeClaim:
          claimName: store-claim