apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
  namespace: default
spec:
  selector:
    matchLabels:
      app: store
  replicas: 2
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
      - name: store
        image: store:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5009
          name: store-container
        volumeMounts:
        - mountPath: /store/storage
          name: store-storage
      volumes:
      - name: store-storage
        persistentVolumeClaim:
          claimName: store-claim