apiVersion: extensions/v1
kind: Deployment
metadata:
  name: store
  namespace: default
spec:
  replicas: 2
  template:
  metadata:
    labels:
    k8s-app: store
  spec:
    containers:
    - name: store-container
      image: store:latest
      imagePullPolicy: "IfNotPresent"
      ports:
      - containerPort: 5035
      volumeMounts:
        - mountPath: /store/storage
          name: store-pv
      volumes:
         - name: store
           persistentVolumeClaim:
             claimName: store-claim